import * as THREE from 'three';
const FIELD=new THREE.Vector3(70,0,70),WIDTH=22,LENGTH=34,GOAL_W=7,GOAL_D=3,MATCH_SECONDS=180;
let scene=null,channelApi=null,myId=null,player=null,ui=null,active=false,team=0,modeLimit=2,players=new Map(),score=[0,0],timeLeft=MATCH_SECONDS,fieldGroup=null,ball=null,ballVel=new THREE.Vector3(),lastUpdate=0,lastGoal=0,startAt=0;
const mat=c=>new THREE.MeshStandardMaterial({color:c});
const worldPos=p=>new THREE.Vector3(FIELD.x+p.x,p.y,FIELD.z+p.z);
function buildField(){fieldGroup=new THREE.Group();fieldGroup.position.copy(FIELD);scene.add(fieldGroup);const ground=new THREE.Mesh(new THREE.BoxGeometry(LENGTH,.2,WIDTH),mat(0x1d7a3a));ground.position.y=.05;ground.receiveShadow=true;fieldGroup.add(ground);const lm=mat(0xffffff),line=(x,z,sx,sz)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(sx,.025,sz),lm);m.position.set(x,.16,z);fieldGroup.add(m);};line(0,-WIDTH/2,LENGTH,.12);line(0,WIDTH/2,LENGTH,.12);line(-LENGTH/2,0,.12,WIDTH);line(LENGTH/2,0,.12,WIDTH);line(0,0,.08,WIDTH);const c=new THREE.Mesh(new THREE.RingGeometry(4.9,5.02,48),lm);c.rotation.x=-Math.PI/2;c.position.y=.17;fieldGroup.add(c);for(const x of [-LENGTH/2,LENGTH/2]){const g=new THREE.Mesh(new THREE.BoxGeometry(GOAL_D,.05,GOAL_W),lm);g.position.set(x<0?x-GOAL_D/2:x+GOAL_D/2,.12,0);g.rotation.y=Math.PI/2;fieldGroup.add(g);}ball=new THREE.Mesh(new THREE.SphereGeometry(.65,16,12),mat(0xffffff));ball.castShadow=true;ball.position.set(0,1,0);fieldGroup.add(ball);}
function clearField(){if(fieldGroup){scene.remove(fieldGroup);fieldGroup=null;}ball=null;}
function renderUi(){if(!ui)return;ui.panel.style.display=active?'block':'none';ui.score.textContent=`${score[0]} - ${score[1]}`;ui.timer.textContent=`${Math.max(0,Math.ceil(timeLeft))}`;ui.mode.textContent=active?`فوتبال ${modeLimit===2?'1v1':'2v2'} | تیم ${team===0?'A':'B'}`:'';}
function spawnPlayers(){for(const p of players.values()){p.mesh?.removeFromParent();const m=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.9,5,8),mat(p.team===0?0x2563eb:0xdc2626));m.position.copy(worldPos(p.pos||new THREE.Vector3()));m.castShadow=true;scene.add(m);p.mesh=m;}}
function assignTeam(){const ids=[...players.keys()].sort();for(let i=0;i<ids.length;i++)players.get(ids[i]).team=i%2;team=players.get(myId)?.team??0;}
function resetPositions(){const ids=[...players.keys()].sort();for(let i=0;i<ids.length;i++){const p=players.get(ids[i]);const isA=p.team===0;p.pos=new THREE.Vector3((isA?-1:1)*12+(i%2)*3,1.05,i%2?5:-5);if(p.mesh)p.mesh.position.copy(worldPos(p.pos));}if(ball)ball.position.set(0,1,0);ballVel.set(0,0,0);startAt=performance.now();}
function localKick(dt){if(!ball||!player)return;const me=players.get(myId);if(!me)return;const dist=ball.position.distanceTo(me.pos);if(dist<2){const dir=new THREE.Vector3(Math.sin(player.yaw),0,-Math.cos(player.yaw));if(dir.lengthSq()<.1)dir.set(team===0?1:-1,0,0);ballVel.addScaledVector(dir,10*dt+1.6);}}
function updateBall(dt){if(!ball)return;ball.position.addScaledVector(ballVel,dt);ballVel.multiplyScalar(Math.pow(.20,dt));ball.position.y=1+Math.sin(Math.min(1,ballVel.length()/8))*.2;const hx=LENGTH/2,hw=WIDTH/2;if(Math.abs(ball.position.z)>hw-.7){ball.position.z=Math.sign(ball.position.z)*(hw-.7);ballVel.z*=-.65;}if(Math.abs(ball.position.x)>hx+.8){if(Math.abs(ball.position.z)<GOAL_W/2&&Math.abs(ball.position.x)<hx+GOAL_D){const scoring=ball.position.x>0?0:1;if(performance.now()-lastGoal>1800){lastGoal=performance.now();score[scoring]++;broadcast({kind:'goal',id:myId,score});resetPositions();}}else{ball.position.x=Math.sign(ball.position.x)*(hx+.8);ballVel.x*=-.65;}}}
const broadcast=payload=>channelApi?.sendFootball(payload);
export function initFootball({scene:sc,player:pl,multiplayer,ui:uis}){scene=sc;player=pl;channelApi=multiplayer;ui=uis;}
export function handleFootballMessage(p){if(p.kind==='start'){modeLimit=p.limit===4?4:2;if(!active)startFootball(modeLimit===4?'2v2':'1v1',true);}if(p.kind==='join'){if(players.size>=modeLimit&&!players.has(p.id))return;players.set(p.id,{id:p.id,team:p.team??0,pos:new THREE.Vector3(p.x||0,1.05,p.z||0)});assignTeam();spawnPlayers();}if(p.kind==='leave'){players.delete(p.id);assignTeam();spawnPlayers();}if(p.kind==='state'&&p.id!==myId){const r=players.get(p.id);if(r){r.pos.set(p.x,p.y,p.z);if(r.mesh)r.mesh.position.copy(worldPos(r.pos));}}if(p.kind==='ball'&&p.id!==myId&&ball){ball.position.set(p.x,p.y,p.z);ballVel.set(p.vx,p.vy,p.vz);}if(p.kind==='goal'&&p.id!==myId){score=[p.score[0],p.score[1]];resetPositions();}renderUi();}
export function startFootball(mode='1v1',remote=false){if(active)return;modeLimit=mode==='2v2'||mode===4?4:2;active=true;score=[0,0];timeLeft=MATCH_SECONDS;players.clear();players.set(myId,{id:myId,team:0,pos:new THREE.Vector3()});assignTeam();buildField();resetPositions();if(!remote)broadcast({kind:'start',id:myId,limit:modeLimit});broadcast({kind:'join',id:myId,team});renderUi();}
export function stopFootball(){if(!active)return;broadcast({kind:'leave',id:myId});active=false;players.clear();clearField();renderUi();}
export function isFootballActive(){return active;}
export function updateFootball(dt){if(!active)return;timeLeft=Math.max(0,MATCH_SECONDS-(performance.now()-startAt)/1000);if(timeLeft<=0){stopFootball();return;}const authority=[...players.keys()].sort()[0]===myId;if(authority){localKick(dt);updateBall(dt);}const me=players.get(myId);if(me){me.pos.set(player.pos.x-FIELD.x,1.05,player.pos.z-FIELD.z);if(me.mesh)me.mesh.position.copy(worldPos(me.pos));if(performance.now()-lastUpdate>80){broadcast({kind:'state',id:myId,x:me.pos.x,y:me.pos.y,z:me.pos.z});lastUpdate=performance.now();}}if(authority&&ball&&performance.now()-lastUpdate>80){broadcast({kind:'ball',id:myId,x:ball.position.x,y:ball.position.y,z:ball.position.z,vx:ballVel.x,vy:ballVel.y,vz:ballVel.z});lastUpdate=performance.now();}renderUi();}
export function getFootballSpawn(){return FIELD.clone();}
