export function setupInput(player,canvas,callbacks){
 const isTouch=('ontouchstart'in window)||navigator.maxTouchPoints>0,keys={},joyVec={x:0,y:0},jumpQueued={value:false};let mouseLocked=false;
 addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Tab'){e.preventDefault();callbacks.toggleBackpack();}if(e.code==='Digit1')callbacks.switchSlot(0);if(e.code==='Digit2')callbacks.switchSlot(1);if(e.code==='Digit3')callbacks.switchSlot(2);if(e.code==='KeyE')callbacks.tryInteract();if(e.code==='KeyR')callbacks.reload();if(e.code==='KeyB')callbacks.toggleBuild();if(e.code==='KeyN')callbacks.cycleBuild();if(e.code==='KeyQ')callbacks.rotateBuild();});
 addEventListener('keyup',e=>keys[e.code]=false);
 canvas.addEventListener('contextmenu',e=>{e.preventDefault();callbacks.toggleBuild();});
 canvas.addEventListener('click',()=>{if(buildModeGuard())return;if(!isTouch&&!mouseLocked)canvas.requestPointerLock();if(mouseLocked||isTouch)callbacks.shoot();});
 function buildModeGuard(){return false;}
 document.addEventListener('pointerlockchange',()=>mouseLocked=document.pointerLockElement===canvas);
 document.addEventListener('mousemove',e=>{if(!mouseLocked)return;player.yaw-=e.movementX*.0022;player.pitch-=e.movementY*.0022;player.pitch=Math.max(-1.35,Math.min(1.35,player.pitch));});
 if(isTouch){const jb=document.getElementById('joyBase'),jk=document.getElementById('joyKnob');let jid=null;jb.addEventListener('touchstart',e=>{jid=e.changedTouches[0].identifier;e.preventDefault()},{passive:false});addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===jid){const r=jb.getBoundingClientRect();let dx=(t.clientX-(r.left+r.width/2))/(r.width/2),dy=(t.clientY-(r.top+r.height/2))/(r.height/2),l=Math.hypot(dx,dy);if(l>1){dx/=l;dy/=l;}joyVec.x=dx;joyVec.y=dy;jk.style.transform=`translate(${dx*32}px,${dy*32}px)`;}},{passive:true});addEventListener('touchend',e=>{for(const t of e.changedTouches)if(t.identifier===jid){jid=null;joyVec.x=0;joyVec.y=0;jk.style.transform='translate(0,0)';}});const lp=document.getElementById('lookPad');let lid=null,last={x:0,y:0};lp.addEventListener('touchstart',e=>{lid=e.changedTouches[0].identifier;last={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===lid){player.yaw-=(t.clientX-last.x)*.0035;player.pitch-=(t.clientY-last.y)*.0035;last={x:t.clientX,y:t.clientY};}},{passive:true});addEventListener('touchend',e=>{for(const t of e.changedTouches)if(t.identifier===lid)lid=null;});document.getElementById('btnJump').addEventListener('touchstart',e=>{e.preventDefault();jumpQueued.value=true},{passive:false});document.getElementById('btnUse').addEventListener('touchstart',e=>{e.preventDefault();callbacks.tryInteract()},{passive:false});document.getElementById('btnShoot').addEventListener('touchstart',e=>{e.preventDefault();callbacks.shoot()},{passive:false});document.getElementById('btnInv').addEventListener('touchstart',e=>{e.preventDefault();callbacks.toggleBackpack()},{passive:false});document.getElementById('mobileUI').style.display='block';}
 return{keys,joyVec,jumpQueued,isTouch,get mouseLocked(){return mouseLocked;}};
}
